# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configAlarm_dise.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(482, 340)
        Dialog.setMouseTracking(False)
        Dialog.setAcceptDrops(False)
        Dialog.setWindowTitle("")
        Dialog.setWindowOpacity(1.0)
        Dialog.setAutoFillBackground(False)
        Dialog.setWindowFilePath("")
        Dialog.setInputMethodHints(QtCore.Qt.ImhNone)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.scroll_alarmas = QtWidgets.QScrollArea(Dialog)
        self.scroll_alarmas.setGeometry(QtCore.QRect(10, 60, 451, 271))
        self.scroll_alarmas.setWidgetResizable(True)
        self.scroll_alarmas.setObjectName("scroll_alarmas")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 449, 269))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_alarmas.setWidget(self.scrollAreaWidgetContents)
        self.btn_agregarItem = QtWidgets.QPushButton(Dialog)
        self.btn_agregarItem.setGeometry(QtCore.QRect(420, 10, 41, 41))
        self.btn_agregarItem.setStyleSheet("QPushButton {\n"
"border-image: url(:/ICON/IMAGENES/add_on.png);\n"
" }\n"
"QPushButton:hover {\n"
"border-image: url(:/ICON/IMAGENES/add_off.png);\n"
"}\n"
"QPushButton:pressed {\n"
"border-image: url(:/ICON/IMAGENES/add_on.png);\n"
"}\n"
"")
        self.btn_agregarItem.setText("")
        self.btn_agregarItem.setObjectName("btn_agregarItem")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        pass
import IMAG_rc
