# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\itemDeber_dise.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(330, 130)
        Form.setMinimumSize(QtCore.QSize(330, 130))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.estadoDeber = QtWidgets.QCheckBox(Form)
        self.estadoDeber.setMinimumSize(QtCore.QSize(40, 40))
        self.estadoDeber.setMaximumSize(QtCore.QSize(70, 70))
        self.estadoDeber.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height:40px;\n"
" }\n"
"\n"
"  QCheckBox::indicator:checked\n"
"  {\n"
"    border-image: url(:/ICON/IMAGENES/check_on.png);\n"
"\n"
"  }\n"
"  QCheckBox::indicator:unchecked\n"
"  {\n"
"    border-image: url(:/ICON/IMAGENES/check_off.png);\n"
"  }\n"
"\n"
"")
        self.estadoDeber.setText("")
        self.estadoDeber.setObjectName("estadoDeber")
        self.horizontalLayout.addWidget(self.estadoDeber)
        self.lineEdit_deber = QtWidgets.QLineEdit(Form)
        self.lineEdit_deber.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_deber.setObjectName("lineEdit_deber")
        self.horizontalLayout.addWidget(self.lineEdit_deber)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import IMAG_rc
