# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\itemAlarmaVista_dise.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 100)
        Form.setMinimumSize(QtCore.QSize(300, 100))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.btn_editar = QtWidgets.QPushButton(Form)
        self.btn_editar.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_editar.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_editar.setStyleSheet("QPushButton {\n"
"    border-image: url(:/ICON/IMAGENES/edit_on.png);\n"
" }\n"
"QPushButton:hover {\n"
"    border-image: url(:/ICON/IMAGENES/edit_off.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/ICON/IMAGENES/edit_on.png);\n"
"}\n"
"")
        self.btn_editar.setText("")
        self.btn_editar.setObjectName("btn_editar")
        self.horizontalLayout_2.addWidget(self.btn_editar)
        self.btn_eliminar = QtWidgets.QPushButton(Form)
        self.btn_eliminar.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_eliminar.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_eliminar.setStyleSheet("QPushButton {\n"
"    border-image: url(:/ICON/IMAGENES/tache_1.png);\n"
" }\n"
"QPushButton:hover {\n"
"border-image: url(:/ICON/IMAGENES/tache_2.png);\n"
"}\n"
"QPushButton:pressed {\n"
"border-image: url(:/ICON/IMAGENES/tache_1.png);\n"
"}\n"
"")
        self.btn_eliminar.setText("")
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout_2.addWidget(self.btn_eliminar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textEdit_alarma = QtWidgets.QTextEdit(Form)
        self.textEdit_alarma.setObjectName("textEdit_alarma")
        self.verticalLayout.addWidget(self.textEdit_alarma)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import IMAG_rc
