# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_dise.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(707, 558)
        self.btn_info = QtWidgets.QPushButton(Form)
        self.btn_info.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.btn_info.setStyleSheet("QPushButton {\n"
"border-image: url(:/ICON/IMAGENES/info_on.png);\n"
" }\n"
"QPushButton:hover {\n"
"border-image: url(:/ICON/IMAGENES/info_off.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/ICON/IMAGENES/info_on.png);\n"
"}\n"
"")
        self.btn_info.setText("")
        self.btn_info.setObjectName("btn_info")
        self.btn_configVenti = QtWidgets.QPushButton(Form)
        self.btn_configVenti.setGeometry(QtCore.QRect(300, 320, 51, 41))
        self.btn_configVenti.setStyleSheet("QPushButton {\n"
"    border-image: url(:/ICON/IMAGENES/config_off.png);\n"
" }\n"
"QPushButton:hover {\n"
"    border-image: url(:/ICON/IMAGENES/config_on.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/ICON/IMAGENES/config_off.png);\n"
"}\n"
"")
        self.btn_configVenti.setText("")
        self.btn_configVenti.setObjectName("btn_configVenti")
        self.btn_configFoco = QtWidgets.QPushButton(Form)
        self.btn_configFoco.setGeometry(QtCore.QRect(530, 320, 51, 41))
        self.btn_configFoco.setStyleSheet("QPushButton {\n"
"    border-image: url(:/ICON/IMAGENES/config_off.png);\n"
" }\n"
"QPushButton:hover {\n"
"    border-image: url(:/ICON/IMAGENES/config_on.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/ICON/IMAGENES/config_off.png);\n"
"}\n"
"")
        self.btn_configFoco.setText("")
        self.btn_configFoco.setObjectName("btn_configFoco")
        self.btn_configIdioma = QtWidgets.QPushButton(Form)
        self.btn_configIdioma.setGeometry(QtCore.QRect(50, 10, 41, 31))
        self.btn_configIdioma.setStyleSheet("QPushButton {\n"
"border-image: url(:/ICON/IMAGENES/idioma_on.png);\n"
" }\n"
"QPushButton:hover {\n"
"border-image: url(:/ICON/IMAGENES/idioma_off.png);\n"
"}\n"
"QPushButton:pressed {\n"
"border-image: url(:/ICON/IMAGENES/idioma_on.png);\n"
"}\n"
"")
        self.btn_configIdioma.setText("")
        self.btn_configIdioma.setObjectName("btn_configIdioma")
        self.hoSli_venti = QtWidgets.QSlider(Form)
        self.hoSli_venti.setGeometry(QtCore.QRect(180, 460, 131, 40))
        self.hoSli_venti.setStyleSheet("QSlider {\n"
"    min-height: 40px;\n"
"    max-height: 40px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #262626;\n"
"    height: 5px;\n"
"    background: #393939;\n"
"    margin: 0 12px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #22B14C;\n"
"    /*background-color: rgb(1, 255, 226);*/\n"
"    /*border: 5px solid #B5E61D;*/\n"
"    width: 15px;\n"
"    height: 80px;\n"
"    margin: 24px -12px;\n"
"}")
        self.hoSli_venti.setMaximum(1)
        self.hoSli_venti.setPageStep(1)
        self.hoSli_venti.setOrientation(QtCore.Qt.Horizontal)
        self.hoSli_venti.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.hoSli_venti.setObjectName("hoSli_venti")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(170, 500, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(280, 500, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(510, 500, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(410, 500, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.hoSli_foco = QtWidgets.QSlider(Form)
        self.hoSli_foco.setGeometry(QtCore.QRect(420, 460, 121, 40))
        self.hoSli_foco.setStyleSheet("QSlider {\n"
"    min-height: 40px;\n"
"    max-height: 40px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #262626;\n"
"    height: 5px;\n"
"    background: #393939;\n"
"    margin: 0 12px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #22B14C;\n"
"    /*background-color: rgb(1, 255, 226);*/\n"
"    /*border: 5px solid #B5E61D;*/\n"
"    width: 15px;\n"
"    height: 80px;\n"
"    margin: 24px -12px;\n"
"}")
        self.hoSli_foco.setMaximum(1)
        self.hoSli_foco.setPageStep(1)
        self.hoSli_foco.setOrientation(QtCore.Qt.Horizontal)
        self.hoSli_foco.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.hoSli_foco.setObjectName("hoSli_foco")
        self.bel_colorFoco = QtWidgets.QLabel(Form)
        self.bel_colorFoco.setGeometry(QtCore.QRect(510, 420, 31, 31))
        self.bel_colorFoco.setMinimumSize(QtCore.QSize(20, 20))
        self.bel_colorFoco.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bel_colorFoco.setFont(font)
        self.bel_colorFoco.setStyleSheet("border :3px solid black;\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 0, 0);")
        self.bel_colorFoco.setText("")
        self.bel_colorFoco.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_colorFoco.setObjectName("bel_colorFoco")
        self.bel_estadoVenti = QtWidgets.QLabel(Form)
        self.bel_estadoVenti.setGeometry(QtCore.QRect(190, 350, 111, 91))
        self.bel_estadoVenti.setStyleSheet("border-image: url(:/ICON/IMAGENES/ventilador_off.png);")
        self.bel_estadoVenti.setText("")
        self.bel_estadoVenti.setObjectName("bel_estadoVenti")
        self.bel_estadoFoco = QtWidgets.QLabel(Form)
        self.bel_estadoFoco.setGeometry(QtCore.QRect(430, 350, 111, 91))
        self.bel_estadoFoco.setStyleSheet("border-image: url(:/ICON/IMAGENES/foco_off.png);")
        self.bel_estadoFoco.setText("")
        self.bel_estadoFoco.setObjectName("bel_estadoFoco")
        self.timeEdit_tiempo = QtWidgets.QTimeEdit(Form)
        self.timeEdit_tiempo.setGeometry(QtCore.QRect(110, 170, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timeEdit_tiempo.setFont(font)
        self.timeEdit_tiempo.setWrapping(False)
        self.timeEdit_tiempo.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_tiempo.setReadOnly(True)
        self.timeEdit_tiempo.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit_tiempo.setObjectName("timeEdit_tiempo")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 250, 81, 51))
        self.pushButton_3.setStyleSheet("border-image: url(:/ICON/IMAGENES/termo.png);\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.bel_temp = QtWidgets.QLabel(Form)
        self.bel_temp.setGeometry(QtCore.QRect(110, 260, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bel_temp.setFont(font)
        self.bel_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_temp.setObjectName("bel_temp")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(200, 260, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.dateEdit_fecha = QtWidgets.QDateEdit(Form)
        self.dateEdit_fecha.setGeometry(QtCore.QRect(110, 100, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dateEdit_fecha.setFont(font)
        self.dateEdit_fecha.setReadOnly(True)
        self.dateEdit_fecha.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit_fecha.setObjectName("dateEdit_fecha")
        self.plaTextEdit_notas = QtWidgets.QPlainTextEdit(Form)
        self.plaTextEdit_notas.setGeometry(QtCore.QRect(310, 100, 371, 211))
        self.plaTextEdit_notas.setObjectName("plaTextEdit_notas")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(320, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.btn_configAlarm = QtWidgets.QPushButton(Form)
        self.btn_configAlarm.setGeometry(QtCore.QRect(640, 40, 41, 41))
        self.btn_configAlarm.setStyleSheet("QPushButton {\n"
"    border-image: url(:/ICON/IMAGENES/alarm_on.png);\n"
" }\n"
"QPushButton:hover {\n"
"    border-image: url(:/ICON/IMAGENES/alarm_off.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/ICON/IMAGENES/alarm_on.png);\n"
"}\n"
"")
        self.btn_configAlarm.setText("")
        self.btn_configAlarm.setObjectName("btn_configAlarm")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(630, 80, 51, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.bel_tempActVenti = QtWidgets.QLabel(Form)
        self.bel_tempActVenti.setGeometry(QtCore.QRect(280, 430, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bel_tempActVenti.setFont(font)
        self.bel_tempActVenti.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_tempActVenti.setObjectName("bel_tempActVenti")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(330, 430, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "OFF"))
        self.label_4.setText(_translate("Form", "ON"))
        self.label_8.setText(_translate("Form", "ON"))
        self.label_9.setText(_translate("Form", "OFF"))
        self.label_6.setText(_translate("Form", "Fecha:"))
        self.bel_temp.setText(_translate("Form", "38"))
        self.label_7.setText(_translate("Form", "Hora:"))
        self.label_2.setText(_translate("Form", "[°C]"))
        self.label_10.setText(_translate("Form", "Recordatorios:"))
        self.label.setText(_translate("Form", "Alarmas"))
        self.bel_tempActVenti.setText(_translate("Form", "38"))
        self.label_5.setText(_translate("Form", "[°C]"))
import IMAG_rc
