# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seccionAlarmas_dise.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(445, 341)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.btn_agregarItem = QtWidgets.QPushButton(Form)
        self.btn_agregarItem.setMinimumSize(QtCore.QSize(25, 30))
        self.btn_agregarItem.setMaximumSize(QtCore.QSize(40, 45))
        self.btn_agregarItem.setStyleSheet("QPushButton {\n"
"    border-image: url(:/ICON/IMAGENES/plus_off.png);\n"
" }\n"
"QPushButton:hover {\n"
"    border-image: url(:/ICON/IMAGENES/plus_on.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/ICON/IMAGENES/plus_off.png);\n"
"}\n"
"")
        self.btn_agregarItem.setText("")
        self.btn_agregarItem.setObjectName("btn_agregarItem")
        self.horizontalLayout.addWidget(self.btn_agregarItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scroll_alarmas = QtWidgets.QScrollArea(Form)
        self.scroll_alarmas.setWidgetResizable(True)
        self.scroll_alarmas.setObjectName("scroll_alarmas")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 425, 283))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_alarmas.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scroll_alarmas)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import IMAG_rc
