
class Recursos_IoT_Domotica():
    #C:\Users\ronal\Desktop\PROYECTO\IoT_domotica\GUI\CUERPO\RECURSOS\MUSICA\DEFAULT
    NOMBRE_BASE_DATOS_ALARMAS="CUERPO/RECURSOS/DATOS/BaseDatosAlarma.db"

    CARPETA_MUSICA="CUERPO/RECURSOS/MUSICA/"
    CARPETA_MUSICA_DEFAULT="DEFAULT/"
    CARPETA_MUSICA_MIA="MIA/"

    NOMBRE_SONIDO_NULL="SIN MUSICA"


