
class Recursos_IoT_Domotica():
    #C:\Users\ronal\Desktop\PROYECTO\IoT_domotica\GUI\CUERPO\RECURSOS\MUSICA\DEFAULT
    
    NOMBRE_BASE_DATOS_ALARMAS="CUERPO/LOGICA/ALARMA/BaseDatosAlarma.db"
    CARPETA_MUSICA_DEFAULT="CUERPO/RECURSOS/MUSICA/DEFAULT/"
    CARPETA_MUSICA_MIA="CUERPO/RECURSOS/MUSICA/MIA/"

