
class Recursos_IoT_Domotica():
    #C:\Users\ronal\Desktop\PROYECTO\IoT_domotica\GUI\CUERPO\RECURSOS\MUSICA\DEFAULT
    NOMBRE_BASE_DATOS_ALARMAS="CUERPO/RECURSOS/DATOS/BaseDatosAlarma.db"
    ARCHIVO_DEBERES="CUERPO/RECURSOS/DATOS/deberes.txt"
    SEPARADOR_DEBERES='^'



    CARPETA_MUSICA="CUERPO/RECURSOS/MUSICA/"
    CARPETA_MUSICA_DEFAULT="DEFAULT/"
    CARPETA_MUSICA_MIA="MIA/"
    NOMBRE_SONIDO_NULL="SIN MUSICA"



    AUDIO_YA_DESPIERTA="CUERPO/RECURSOS/SONIDOS_SISTEMA/hora_despertar.wav"
    AUDIO_IR_DORMIR="CUERPO/RECURSOS/SONIDOS_SISTEMA/hora_dormir.wav"
    AUDIO_HAZ_DEBERES="CUERPO/RECURSOS/SONIDOS_SISTEMA/hora_deberes.wav"
    SONIDO_INCENDIO="CUERPO/RECURSOS/SONIDOS_SISTEMA/fuego_detectado.mp3"


