# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_dise.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(733, 507)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 90, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(560, 10, 51, 41))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"border-image: url(:/ICON/IMAGENES/info_on.png);\n"
" }\n"
"QPushButton:hover {\n"
"border-image: url(:/ICON/IMAGENES/info_off.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/ICON/IMAGENES/info_on.png);\n"
"}\n"
"")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 200, 81, 51))
        self.pushButton_3.setStyleSheet("border-image: url(:/ICON/IMAGENES/termo.png);\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(350, 90, 301, 191))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(160, 320, 51, 41))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    border-image: url(:/ICON/IMAGENES/config_off.png);\n"
" }\n"
"QPushButton:hover {\n"
"    border-image: url(:/ICON/IMAGENES/config_on.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/ICON/IMAGENES/config_off.png);\n"
"}\n"
"")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(530, 330, 121, 111))
        self.pushButton_5.setStyleSheet("border-image: url(:/ICON/IMAGENES/foco_off.png);\n"
"")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(300, 340, 121, 101))
        self.pushButton_8.setStyleSheet("border-image: url(:/ICON/IMAGENES/ventilador_off.png);\n"
"\n"
"")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 210, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(410, 320, 51, 41))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    border-image: url(:/ICON/IMAGENES/config_off.png);\n"
" }\n"
"QPushButton:hover {\n"
"    border-image: url(:/ICON/IMAGENES/config_on.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/ICON/IMAGENES/config_off.png);\n"
"}\n"
"")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(340, 50, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 210, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 330, 161, 141))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"border-image: url(:/ICON/IMAGENES/alarm_off.png);\n"
" }\n"
"QPushButton:hover {\n"
"border-image: url(:/ICON/IMAGENES/alarm_on.png);\n"
"}\n"
"QPushButton:pressed {\n"
"border-image: url(:/ICON/IMAGENES/alarm_off.png);\n"
"}\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(640, 310, 51, 41))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    border-image: url(:/ICON/IMAGENES/config_off.png);\n"
" }\n"
"QPushButton:hover {\n"
"    border-image: url(:/ICON/IMAGENES/config_on.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/ICON/IMAGENES/config_off.png);\n"
"}\n"
"")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(630, 10, 61, 41))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"border-image: url(:/ICON/IMAGENES/idioma_on.png);\n"
" }\n"
"QPushButton:hover {\n"
"border-image: url(:/ICON/IMAGENES/idioma_off.png);\n"
"}\n"
"QPushButton:pressed {\n"
"border-image: url(:/ICON/IMAGENES/idioma_on.png);\n"
"}\n"
"")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setGeometry(QtCore.QRect(120, 80, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dateEdit.setFont(font)
        self.dateEdit.setReadOnly(True)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit = QtWidgets.QTimeEdit(Form)
        self.timeEdit.setGeometry(QtCore.QRect(120, 140, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timeEdit.setFont(font)
        self.timeEdit.setWrapping(False)
        self.timeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(310, 450, 101, 16))
        self.horizontalSlider.setMaximum(1)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(290, 470, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(380, 470, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(610, 470, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(520, 470, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalSlider_2 = QtWidgets.QSlider(Form)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(540, 450, 101, 16))
        self.horizontalSlider_2.setMaximum(1)
        self.horizontalSlider_2.setPageStep(1)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Fecha:"))
        self.label_2.setText(_translate("Form", "[°C]"))
        self.label_7.setText(_translate("Form", "Hora:"))
        self.label_5.setText(_translate("Form", "Notas:"))
        self.label.setText(_translate("Form", "38"))
        self.label_3.setText(_translate("Form", "OFF"))
        self.label_4.setText(_translate("Form", "ON"))
        self.label_8.setText(_translate("Form", "ON"))
        self.label_9.setText(_translate("Form", "OFF"))
import IMAG_rc
