# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\configLed_dise.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(468, 210)
        Dialog.setMouseTracking(False)
        Dialog.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/IoT_domotica.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(1.0)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color: #d8d8d8;")
        Dialog.setWindowFilePath("")
        Dialog.setInputMethodHints(QtCore.Qt.ImhNone)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("TamilSangamMN")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("  font-family: TamilSangamMN;\n"
"  font-size: 20px;")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMinimumSize(QtCore.QSize(0, 10))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bel_colorFoco = QtWidgets.QLabel(Dialog)
        self.bel_colorFoco.setMinimumSize(QtCore.QSize(90, 60))
        self.bel_colorFoco.setMaximumSize(QtCore.QSize(160, 120))
        self.bel_colorFoco.setBaseSize(QtCore.QSize(60, 50))
        self.bel_colorFoco.setStyleSheet("border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/foco1_blanco.png);")
        self.bel_colorFoco.setText("")
        self.bel_colorFoco.setObjectName("bel_colorFoco")
        self.horizontalLayout.addWidget(self.bel_colorFoco)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(0, 5))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_3.setBaseSize(QtCore.QSize(0, 5))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(350, 55))
        self.widget.setMaximumSize(QtCore.QSize(720, 120))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_0 = QtWidgets.QPushButton(self.widget)
        self.btn_0.setMinimumSize(QtCore.QSize(45, 45))
        self.btn_0.setMaximumSize(QtCore.QSize(200, 200))
        self.btn_0.setBaseSize(QtCore.QSize(50, 50))
        self.btn_0.setStyleSheet("border :1px solid black;\n"
"border-radius: 22%;\n"
"background-color: rgb(255,255,255);\n"
"\n"
"  \n"
"  ")
        self.btn_0.setText("")
        self.btn_0.setObjectName("btn_0")
        self.horizontalLayout_2.addWidget(self.btn_0)
        self.btn_1 = QtWidgets.QPushButton(self.widget)
        self.btn_1.setMinimumSize(QtCore.QSize(45, 45))
        self.btn_1.setMaximumSize(QtCore.QSize(200, 200))
        self.btn_1.setBaseSize(QtCore.QSize(50, 50))
        self.btn_1.setStyleSheet("border :1px solid black;\n"
"border-radius: 22%;\n"
"background-color: rgb(255, 0, 0);")
        self.btn_1.setText("")
        self.btn_1.setObjectName("btn_1")
        self.horizontalLayout_2.addWidget(self.btn_1)
        self.btn_2 = QtWidgets.QPushButton(self.widget)
        self.btn_2.setMinimumSize(QtCore.QSize(45, 45))
        self.btn_2.setMaximumSize(QtCore.QSize(200, 200))
        self.btn_2.setBaseSize(QtCore.QSize(50, 50))
        self.btn_2.setStyleSheet("border :1px solid black;\n"
"border-radius: 22%;\n"
"background-color: rgb(0,255, 0);")
        self.btn_2.setText("")
        self.btn_2.setObjectName("btn_2")
        self.horizontalLayout_2.addWidget(self.btn_2)
        self.btn_3 = QtWidgets.QPushButton(self.widget)
        self.btn_3.setMinimumSize(QtCore.QSize(45, 45))
        self.btn_3.setMaximumSize(QtCore.QSize(200, 200))
        self.btn_3.setBaseSize(QtCore.QSize(50, 50))
        self.btn_3.setStyleSheet("border :1px solid black;\n"
"border-radius: 22%;\n"
"background-color: rgb(0,0,255);")
        self.btn_3.setText("")
        self.btn_3.setObjectName("btn_3")
        self.horizontalLayout_2.addWidget(self.btn_3)
        self.btn_4 = QtWidgets.QPushButton(self.widget)
        self.btn_4.setMinimumSize(QtCore.QSize(45, 45))
        self.btn_4.setMaximumSize(QtCore.QSize(200, 200))
        self.btn_4.setBaseSize(QtCore.QSize(50, 50))
        self.btn_4.setStyleSheet("border :1px solid black;\n"
"border-radius: 22%;\n"
"background-color: rgb(255,255, 0);")
        self.btn_4.setText("")
        self.btn_4.setObjectName("btn_4")
        self.horizontalLayout_2.addWidget(self.btn_4)
        self.btn_5 = QtWidgets.QPushButton(self.widget)
        self.btn_5.setMinimumSize(QtCore.QSize(45, 45))
        self.btn_5.setMaximumSize(QtCore.QSize(200, 200))
        self.btn_5.setBaseSize(QtCore.QSize(50, 50))
        self.btn_5.setStyleSheet("border :1px solid black;\n"
"border-radius: 22%;\n"
"background-color: rgb(255, 0, 255);")
        self.btn_5.setText("")
        self.btn_5.setObjectName("btn_5")
        self.horizontalLayout_2.addWidget(self.btn_5)
        self.btn_6 = QtWidgets.QPushButton(self.widget)
        self.btn_6.setMinimumSize(QtCore.QSize(45, 45))
        self.btn_6.setMaximumSize(QtCore.QSize(200, 200))
        self.btn_6.setBaseSize(QtCore.QSize(50, 50))
        self.btn_6.setStyleSheet("border :1px solid black;\n"
"border-radius: 22%;\n"
"background-color: rgb(0,255,255);")
        self.btn_6.setText("")
        self.btn_6.setObjectName("btn_6")
        self.horizontalLayout_2.addWidget(self.btn_6)
        self.verticalLayout.addWidget(self.widget)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(0, 5))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_4.setBaseSize(QtCore.QSize(0, 5))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(0, 5))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMinimumSize(QtCore.QSize(0, 5))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.bel_aplicarColor = QtWidgets.QLabel(Dialog)
        self.bel_aplicarColor.setMinimumSize(QtCore.QSize(0, 20))
        self.bel_aplicarColor.setMaximumSize(QtCore.QSize(70, 20))
        self.bel_aplicarColor.setStyleSheet("  opacity: 0.99;\n"
"  font-family: TamilSangamMN;\n"
"  font-size: 15px;\n"
"  font-weight: bold;\n"
"  font-stretch: normal;\n"
"  color: #000000;\n"
"  margin-rigth:20px")
        self.bel_aplicarColor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bel_aplicarColor.setObjectName("bel_aplicarColor")
        self.horizontalLayout_5.addWidget(self.bel_aplicarColor)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setMinimumSize(QtCore.QSize(5, 5))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "RoniHernandez99/IoT_domotica "))
        self.label.setText(_translate("Dialog", "Selecciona el color de luz que deseas"))
        self.bel_aplicarColor.setText(_translate("Dialog", "Aplicar "))
import IMAG_rc
