# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\configVenti_dise.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(375, 146)
        Dialog.setMouseTracking(False)
        Dialog.setAcceptDrops(False)
        Dialog.setWindowTitle("")
        Dialog.setWindowOpacity(1.0)
        Dialog.setAutoFillBackground(False)
        Dialog.setWindowFilePath("")
        Dialog.setInputMethodHints(QtCore.Qt.ImhNone)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(9, 9, 351, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.dSB_tempActVenti = QtWidgets.QDoubleSpinBox(Dialog)
        self.dSB_tempActVenti.setGeometry(QtCore.QRect(110, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dSB_tempActVenti.setFont(font)
        self.dSB_tempActVenti.setAlignment(QtCore.Qt.AlignCenter)
        self.dSB_tempActVenti.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dSB_tempActVenti.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dSB_tempActVenti.setKeyboardTracking(True)
        self.dSB_tempActVenti.setProperty("showGroupSeparator", False)
        self.dSB_tempActVenti.setDecimals(1)
        self.dSB_tempActVenti.setProperty("value", 70.0)
        self.dSB_tempActVenti.setObjectName("dSB_tempActVenti")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(190, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.btn_guardarSalir = QtWidgets.QPushButton(Dialog)
        self.btn_guardarSalir.setGeometry(QtCore.QRect(150, 110, 101, 31))
        self.btn_guardarSalir.setObjectName("btn_guardarSalir")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(230, 50, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/termo.png);")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Dialog", "Prender ventilador a partir de los:"))
        self.label_2.setText(_translate("Dialog", "°[C]"))
        self.btn_guardarSalir.setText(_translate("Dialog", "Guardar cambios"))
import IMAG_rc
