# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\datosCreador_dise.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 400)
        Dialog.setMinimumSize(QtCore.QSize(400, 400))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser_datosCreador = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_datosCreador.setObjectName("textBrowser_datosCreador")
        self.verticalLayout.addWidget(self.textBrowser_datosCreador)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowser_datosCreador.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<h1 style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Programador: Roni Hernandez </span></h1>\n"
"<h1 align=\"center\" style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/yoMero.jpg\" /><span style=\" font-size:8pt; font-weight:600;\"> </span></h1>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Gmail:ronaldo.runing.r@gmail.com </span></h3>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Liked in: </span><a href=\"https://www.linkedin.com/in/roni-hern%C3%A1ndez-613a62173/\"><span style=\" font-size:8pt; font-weight:600; text-decoration: underline; color:#0000ff;\">Roni Hernández </span></a></h3>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Github: </span><a href=\"https://github.com/RoniHernandez99\"><span style=\" font-size:8pt; font-weight:600; text-decoration: underline; color:#0000ff;\">RoniHernandez99 </span></a></h3>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Repositorio de todo el proyecto: </span><a href=\"https://github.com/RoniHernandez99\"><span style=\" font-size:8pt; font-weight:600; text-decoration: underline; color:#0000ff;\">IoT_domotica </span></a></h3></body></html>"))
import IMAG_rc
