# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_dise.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(761, 533)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_info = QtWidgets.QPushButton(Form)
        self.btn_info.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_info.setMaximumSize(QtCore.QSize(35, 35))
        self.btn_info.setStyleSheet("\n"
"QPushButton {\n"
"border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/info_on.png);\n"
" }\n"
"QPushButton:hover {\n"
"border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/info_off.png);\n"
"}\n"
"QPushButton:pressed {\n"
"border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/info_on.png);\n"
"}\n"
"")
        self.btn_info.setText("")
        self.btn_info.setObjectName("btn_info")
        self.horizontalLayout_4.addWidget(self.btn_info)
        self.btn_configIdioma = QtWidgets.QPushButton(Form)
        self.btn_configIdioma.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_configIdioma.setMaximumSize(QtCore.QSize(35, 35))
        self.btn_configIdioma.setStyleSheet("QPushButton {\n"
"border-image:url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/idioma_on.png)\n"
" }\n"
"QPushButton:hover {\n"
"border-image:url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/idioma_off.png)\n"
"}\n"
"QPushButton:pressed {\n"
"border-image:url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/idioma_on.png)\n"
"}\n"
"")
        self.btn_configIdioma.setText("")
        self.btn_configIdioma.setObjectName("btn_configIdioma")
        self.horizontalLayout_4.addWidget(self.btn_configIdioma)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(80, 30))
        self.label_6.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.dateEdit_fecha = QtWidgets.QDateEdit(Form)
        self.dateEdit_fecha.setMinimumSize(QtCore.QSize(160, 40))
        self.dateEdit_fecha.setMaximumSize(QtCore.QSize(250, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dateEdit_fecha.setFont(font)
        self.dateEdit_fecha.setReadOnly(True)
        self.dateEdit_fecha.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit_fecha.setObjectName("dateEdit_fecha")
        self.horizontalLayout_3.addWidget(self.dateEdit_fecha)
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setMinimumSize(QtCore.QSize(10, 0))
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_3.addWidget(self.label_26)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setMinimumSize(QtCore.QSize(80, 30))
        self.label_7.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.timeEdit_tiempo = QtWidgets.QTimeEdit(Form)
        self.timeEdit_tiempo.setMinimumSize(QtCore.QSize(160, 40))
        self.timeEdit_tiempo.setMaximumSize(QtCore.QSize(250, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timeEdit_tiempo.setFont(font)
        self.timeEdit_tiempo.setWrapping(False)
        self.timeEdit_tiempo.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_tiempo.setReadOnly(True)
        self.timeEdit_tiempo.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit_tiempo.setObjectName("timeEdit_tiempo")
        self.horizontalLayout_2.addWidget(self.timeEdit_tiempo)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setMinimumSize(QtCore.QSize(10, 0))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(80, 50))
        self.label_4.setMaximumSize(QtCore.QSize(150, 90))
        self.label_4.setStyleSheet("border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/termo.png);\n"
"padding:0px;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.bel_temp = QtWidgets.QLabel(Form)
        self.bel_temp.setMinimumSize(QtCore.QSize(80, 50))
        self.bel_temp.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bel_temp.setFont(font)
        self.bel_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_temp.setObjectName("bel_temp")
        self.horizontalLayout.addWidget(self.bel_temp)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(60, 50))
        self.label_2.setMaximumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setMinimumSize(QtCore.QSize(10, 0))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout.addWidget(self.label_29)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(150, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.rb_controlManual = QtWidgets.QRadioButton(Form)
        self.rb_controlManual.setMinimumSize(QtCore.QSize(120, 20))
        self.rb_controlManual.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rb_controlManual.setFont(font)
        self.rb_controlManual.setObjectName("rb_controlManual")
        self.verticalLayout_2.addWidget(self.rb_controlManual)
        self.rb_controlAutomatico = QtWidgets.QRadioButton(Form)
        self.rb_controlAutomatico.setMinimumSize(QtCore.QSize(120, 20))
        self.rb_controlAutomatico.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rb_controlAutomatico.setFont(font)
        self.rb_controlAutomatico.setObjectName("rb_controlAutomatico")
        self.verticalLayout_2.addWidget(self.rb_controlAutomatico)
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.verticalLayout_2.addWidget(self.label_35)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setMinimumSize(QtCore.QSize(10, 0))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_5.addWidget(self.label_30)
        self.line = QtWidgets.QFrame(Form)
        self.line.setStyleSheet("border: 5px solid black;")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setMinimumSize(QtCore.QSize(10, 0))
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_5.addWidget(self.label_28)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMinimumSize(QtCore.QSize(390, 300))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 450))
        self.tabWidget.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"/* La linea encabezado que se encuentra abajo de los cuadros de seleccion*/\n"
"    border-top: 2px solid #C2C7CB;\n"
"}\n"
"\n"
"QTabWidget::tab-bar { \n"
"/*Que tan alejado se encuentra el primer cuadro de seleccion de la parte izquierda del TabWiget*/\n"
"   left: 5px; /* move to the right by 5px */\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 2px solid #C4C4C3; /*contorno de los cuadros de seleccion*/\n"
"   \n"
" /*linea de abajo del cuadro(s) que no esta(n) seleccionado(s)*/\n"
"    border-bottom-color:#C2C7CB; /* same as the pane color */\n"
"\n"
"    border-top-left-radius: 10px; /*curvatura de los cuadros de seleccion*/\n"
"    border-top-right-radius: 4px; /*curvatura de los cuadros de seleccion*/\n"
"    min-width: 25ex; /*ancho de cada casila*/\n"
"    min-height:5ex;/*alto de cada casilla*/\n"
"    padding: 2px;\n"
"   font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color:#9B9B9B;/*Color del borde de la casilla que esta seleccionada*/\n"
"   /*borde del suelo del cuadro que esta seleccionado*/ \n"
"   border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"   /*tamaño de superiodida de alto del cuadro seleccionado y los que no*/\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"    font: 14pt \"MS Shell Dlg 2\"; /*Tamaño de letra de los cuadros que no estan\n"
"   seleccionados*/\n"
"}\n"
"\n"
"/* make use of negative margins for overlapping tabs */\n"
"QTabBar::tab:selected {\n"
"    /* expand/overlap to the left and right by 4px */\n"
"    margin-left: -4px;/*longitud que se alejara una casilla de la parte izquierda \n"
"   cuando este seleccionada*/\n"
"    margin-right: -4px;\n"
"}\n"
"\n"
"QTabBar::tab:first:selected {\n"
"    margin-left: 0; /* the first selected tab has nothing to overlap with on the left */\n"
"}\n"
"\n"
"QTabBar::tab:last:selected {\n"
" margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"    margin: 0; /* if there is only one tab, we don\'t want overlapping margins */\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setMinimumSize(QtCore.QSize(10, 0))
        self.label_21.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_10.addWidget(self.label_21)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setMaximumSize(QtCore.QSize(30, 40))
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_12.addWidget(self.label_27)
        self.btn_configVenti = QtWidgets.QPushButton(Form)
        self.btn_configVenti.setMinimumSize(QtCore.QSize(110, 30))
        self.btn_configVenti.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_configVenti.setFont(font)
        self.btn_configVenti.setObjectName("btn_configVenti")
        self.horizontalLayout_12.addWidget(self.btn_configVenti)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setMinimumSize(QtCore.QSize(0, 5))
        self.label_8.setMaximumSize(QtCore.QSize(150, 10))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.bel_estadoVenti = QtWidgets.QLabel(Form)
        self.bel_estadoVenti.setMinimumSize(QtCore.QSize(100, 70))
        self.bel_estadoVenti.setMaximumSize(QtCore.QSize(130, 100))
        self.bel_estadoVenti.setStyleSheet("border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/ventilador_off.png);\n"
"")
        self.bel_estadoVenti.setText("")
        self.bel_estadoVenti.setObjectName("bel_estadoVenti")
        self.verticalLayout_6.addWidget(self.bel_estadoVenti)
        self.hoSli_venti = QtWidgets.QSlider(Form)
        self.hoSli_venti.setMinimumSize(QtCore.QSize(0, 40))
        self.hoSli_venti.setMaximumSize(QtCore.QSize(130, 40))
        self.hoSli_venti.setStyleSheet("QSlider {\n"
"    min-height: 40px;\n"
"    max-height: 40px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #262626;\n"
"    height: 5px;\n"
"   /* background: #393939;*/\n"
"    background:#95DEE7;\n"
"    margin: 0 12px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"   /* background: #22B14C;*/\n"
"    background:#95DEE7;\n"
"    width: 15px;\n"
"    height: 80px;\n"
"    margin: 24px -12px;\n"
"}")
        self.hoSli_venti.setMaximum(1)
        self.hoSli_venti.setPageStep(1)
        self.hoSli_venti.setOrientation(QtCore.Qt.Horizontal)
        self.hoSli_venti.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.hoSli_venti.setObjectName("hoSli_venti")
        self.verticalLayout_6.addWidget(self.hoSli_venti)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setMinimumSize(QtCore.QSize(40, 30))
        self.label_23.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_11.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setMinimumSize(QtCore.QSize(0, 30))
        self.label_24.setMaximumSize(QtCore.QSize(50, 30))
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setMinimumSize(QtCore.QSize(40, 30))
        self.label_25.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_11.addWidget(self.label_25)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setMinimumSize(QtCore.QSize(10, 0))
        self.label_20.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setMaximumSize(QtCore.QSize(90, 40))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.btn_configFoco = QtWidgets.QPushButton(Form)
        self.btn_configFoco.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_configFoco.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_configFoco.setStyleSheet("border :3px solid black;\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 0, 0);")
        self.btn_configFoco.setText("")
        self.btn_configFoco.setObjectName("btn_configFoco")
        self.horizontalLayout_9.addWidget(self.btn_configFoco)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setMinimumSize(QtCore.QSize(0, 5))
        self.label_31.setMaximumSize(QtCore.QSize(150, 10))
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_3.addWidget(self.label_31)
        self.bel_estadoFoco = QtWidgets.QLabel(Form)
        self.bel_estadoFoco.setMinimumSize(QtCore.QSize(100, 70))
        self.bel_estadoFoco.setMaximumSize(QtCore.QSize(130, 120))
        self.bel_estadoFoco.setStyleSheet("border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/foco_off.png);")
        self.bel_estadoFoco.setText("")
        self.bel_estadoFoco.setObjectName("bel_estadoFoco")
        self.verticalLayout_3.addWidget(self.bel_estadoFoco)
        self.hoSli_foco = QtWidgets.QSlider(Form)
        self.hoSli_foco.setMaximumSize(QtCore.QSize(130, 40))
        self.hoSli_foco.setStyleSheet("QSlider {\n"
"    min-height: 40px;\n"
"    max-height: 40px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #262626;\n"
"    height: 5px;\n"
"   /* background: #393939;*/\n"
"    background:#95DEE7;\n"
"    margin: 0 12px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"   /* background: #22B14C;*/\n"
"    background:#95DEE7;\n"
"    width: 15px;\n"
"    height: 80px;\n"
"    margin: 24px -12px;\n"
"}")
        self.hoSli_foco.setMaximum(1)
        self.hoSli_foco.setPageStep(1)
        self.hoSli_foco.setOrientation(QtCore.Qt.Horizontal)
        self.hoSli_foco.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.hoSli_foco.setObjectName("hoSli_foco")
        self.verticalLayout_3.addWidget(self.hoSli_foco)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setMinimumSize(QtCore.QSize(40, 30))
        self.label_17.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setMinimumSize(QtCore.QSize(0, 30))
        self.label_18.setMaximumSize(QtCore.QSize(50, 30))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setMinimumSize(QtCore.QSize(40, 30))
        self.label_19.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setMinimumSize(QtCore.QSize(10, 0))
        self.label_22.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setMinimumSize(QtCore.QSize(10, 0))
        self.label_16.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Fecha:"))
        self.label_7.setText(_translate("Form", "Hora:"))
        self.bel_temp.setText(_translate("Form", "38.00"))
        self.label_2.setText(_translate("Form", "[°C]"))
        self.label_3.setText(_translate("Form", "Control"))
        self.rb_controlManual.setText(_translate("Form", "Manual"))
        self.rb_controlAutomatico.setText(_translate("Form", "Automatico"))
        self.btn_configVenti.setText(_translate("Form", "100 [°C]"))
        self.label_23.setText(_translate("Form", "OFF"))
        self.label_25.setText(_translate("Form", "ON"))
        self.label_17.setText(_translate("Form", "OFF"))
        self.label_19.setText(_translate("Form", "ON"))
import IMAG_rc
