# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_dise.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(823, 518)
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Mexico))
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(320, 500))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_info = QtWidgets.QPushButton(self.widget)
        self.btn_info.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_info.setMaximumSize(QtCore.QSize(35, 35))
        self.btn_info.setStyleSheet("\n"
"QPushButton {\n"
"border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/info_on.png);\n"
" }\n"
"QPushButton:hover {\n"
"border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/info_off.png);\n"
"}\n"
"QPushButton:pressed {\n"
"border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/info_on.png);\n"
"}\n"
"")
        self.btn_info.setText("")
        self.btn_info.setObjectName("btn_info")
        self.horizontalLayout_4.addWidget(self.btn_info)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_40 = QtWidgets.QLabel(self.widget)
        self.label_40.setMinimumSize(QtCore.QSize(100, 10))
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.verticalLayout.addWidget(self.label_40)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dateEdit_fecha = QtWidgets.QDateEdit(self.widget)
        self.dateEdit_fecha.setMinimumSize(QtCore.QSize(200, 40))
        self.dateEdit_fecha.setMaximumSize(QtCore.QSize(600, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateEdit_fecha.setFont(font)
        self.dateEdit_fecha.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Mexico))
        self.dateEdit_fecha.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_fecha.setReadOnly(True)
        self.dateEdit_fecha.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit_fecha.setProperty("showGroupSeparator", False)
        self.dateEdit_fecha.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 9, 13), QtCore.QTime(0, 0, 0)))
        self.dateEdit_fecha.setCalendarPopup(False)
        self.dateEdit_fecha.setObjectName("dateEdit_fecha")
        self.horizontalLayout_3.addWidget(self.dateEdit_fecha)
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setMinimumSize(QtCore.QSize(10, 0))
        self.label_26.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_3.addWidget(self.label_26)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_39 = QtWidgets.QLabel(self.widget)
        self.label_39.setMinimumSize(QtCore.QSize(100, 10))
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.verticalLayout.addWidget(self.label_39)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.timeEdit_tiempo = QtWidgets.QTimeEdit(self.widget)
        self.timeEdit_tiempo.setMinimumSize(QtCore.QSize(160, 40))
        self.timeEdit_tiempo.setMaximumSize(QtCore.QSize(600, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.timeEdit_tiempo.setFont(font)
        self.timeEdit_tiempo.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Mexico))
        self.timeEdit_tiempo.setWrapping(False)
        self.timeEdit_tiempo.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit_tiempo.setReadOnly(True)
        self.timeEdit_tiempo.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit_tiempo.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(7, 0, 0)))
        self.timeEdit_tiempo.setObjectName("timeEdit_tiempo")
        self.horizontalLayout_2.addWidget(self.timeEdit_tiempo)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setMinimumSize(QtCore.QSize(10, 0))
        self.label_14.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_38 = QtWidgets.QLabel(self.widget)
        self.label_38.setMinimumSize(QtCore.QSize(100, 10))
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.verticalLayout.addWidget(self.label_38)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(80, 50))
        self.label_4.setMaximumSize(QtCore.QSize(150, 90))
        self.label_4.setStyleSheet("border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/termo.png);\n"
"padding:0px;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.bel_temp = QtWidgets.QLabel(self.widget)
        self.bel_temp.setMinimumSize(QtCore.QSize(80, 50))
        self.bel_temp.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bel_temp.setFont(font)
        self.bel_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_temp.setObjectName("bel_temp")
        self.horizontalLayout.addWidget(self.bel_temp)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(60, 50))
        self.label_2.setMaximumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_29 = QtWidgets.QLabel(self.widget)
        self.label_29.setMinimumSize(QtCore.QSize(10, 0))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout.addWidget(self.label_29)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setMinimumSize(QtCore.QSize(100, 10))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(150, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.rb_controlManual = QtWidgets.QRadioButton(self.widget)
        self.rb_controlManual.setMinimumSize(QtCore.QSize(120, 20))
        self.rb_controlManual.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rb_controlManual.setFont(font)
        self.rb_controlManual.setObjectName("rb_controlManual")
        self.verticalLayout.addWidget(self.rb_controlManual)
        self.rb_controlAutomatico = QtWidgets.QRadioButton(self.widget)
        self.rb_controlAutomatico.setMinimumSize(QtCore.QSize(120, 20))
        self.rb_controlAutomatico.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rb_controlAutomatico.setFont(font)
        self.rb_controlAutomatico.setObjectName("rb_controlAutomatico")
        self.verticalLayout.addWidget(self.rb_controlAutomatico)
        self.label_41 = QtWidgets.QLabel(self.widget)
        self.label_41.setMinimumSize(QtCore.QSize(100, 10))
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.verticalLayout.addWidget(self.label_41)
        self.horizontalLayout_10.addWidget(self.widget)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setMinimumSize(QtCore.QSize(10, 0))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_10.addWidget(self.label_30)
        self.line = QtWidgets.QFrame(Form)
        self.line.setStyleSheet("border: 5px solid black;")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_10.addWidget(self.line)
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setMinimumSize(QtCore.QSize(10, 0))
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_10.addWidget(self.label_28)
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setMinimumSize(QtCore.QSize(400, 500))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_4)
        self.tabWidget.setMinimumSize(QtCore.QSize(390, 250))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 600))
        self.tabWidget.setStyleSheet("\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"/* La linea encabezado que se encuentra abajo de los cuadros de seleccion*/\n"
"    border-top: 2px solid #C2C7CB;\n"
"}\n"
"\n"
"QTabWidget::tab-bar { \n"
"/*Que tan alejado se encuentra el primer cuadro de seleccion de la parte izquierda del TabWiget*/\n"
"   left: 5px; /* move to the right by 5px */\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 2px solid #C4C4C3; /*contorno de los cuadros de seleccion*/\n"
"   \n"
" /*linea de abajo del cuadro(s) que no esta(n) seleccionado(s)*/\n"
"    border-bottom-color:#C2C7CB; /* same as the pane color */\n"
"\n"
"    border-top-left-radius: 10px; /*curvatura de los cuadros de seleccion*/\n"
"    border-top-right-radius: 4px; /*curvatura de los cuadros de seleccion*/\n"
"    min-width: 150px; /*ancho de cada casila*/\n"
"    min-height:40px;/*alto de cada casilla*/\n"
"    padding: 2px;\n"
"   font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color:#9B9B9B;/*Color del borde de la casilla que esta seleccionada*/\n"
"   /*borde del suelo del cuadro que esta seleccionado*/ \n"
"   border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"   /*tamaño de superiodida de alto del cuadro seleccionado y los que no*/\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"    font: 14pt \"MS Shell Dlg 2\"; /*Tamaño de letra de los cuadros que no estan\n"
"   seleccionados*/\n"
"}\n"
"\n"
"/* make use of negative margins for overlapping tabs */\n"
"QTabBar::tab:selected {\n"
"    /* expand/overlap to the left and right by 4px */\n"
"    margin-left: -4px;/*longitud que se alejara una casilla de la parte izquierda \n"
"   cuando este seleccionada*/\n"
"    margin-right: -4px;\n"
"}\n"
"\n"
"QTabBar::tab:first:selected {\n"
"    margin-left: 0; /* the first selected tab has nothing to overlap with on the left */\n"
"}\n"
"\n"
"QTabBar::tab:last:selected {\n"
" margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"    margin: 0; /* if there is only one tab, we don\'t want overlapping margins */\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setMinimumSize(QtCore.QSize(291, 200))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_3 = QtWidgets.QWidget(self.widget_5)
        self.widget_3.setMinimumSize(QtCore.QSize(150, 180))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setMaximumSize(QtCore.QSize(100, 40))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.btn_configFoco = QtWidgets.QPushButton(self.widget_3)
        self.btn_configFoco.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_configFoco.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_configFoco.setStyleSheet("border :3px solid black;\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 0, 0);")
        self.btn_configFoco.setText("")
        self.btn_configFoco.setObjectName("btn_configFoco")
        self.horizontalLayout_9.addWidget(self.btn_configFoco)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_34 = QtWidgets.QLabel(self.widget_3)
        self.label_34.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_8.addWidget(self.label_34)
        self.bel_estadoFoco = QtWidgets.QLabel(self.widget_3)
        self.bel_estadoFoco.setMinimumSize(QtCore.QSize(100, 70))
        self.bel_estadoFoco.setMaximumSize(QtCore.QSize(150, 150))
        self.bel_estadoFoco.setStyleSheet("border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/foco_off.png);")
        self.bel_estadoFoco.setText("")
        self.bel_estadoFoco.setObjectName("bel_estadoFoco")
        self.horizontalLayout_8.addWidget(self.bel_estadoFoco)
        self.label_35 = QtWidgets.QLabel(self.widget_3)
        self.label_35.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_8.addWidget(self.label_35)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_36 = QtWidgets.QLabel(self.widget_3)
        self.label_36.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_13.addWidget(self.label_36)
        self.hoSli_foco = QtWidgets.QSlider(self.widget_3)
        self.hoSli_foco.setMinimumSize(QtCore.QSize(100, 35))
        self.hoSli_foco.setMaximumSize(QtCore.QSize(120, 16777215))
        self.hoSli_foco.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: white;\n"
"height: 25px; /*ALTURA DE LA BARRA*/\n"
"border-radius: 4px;\n"
"text:\"roni\";\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);\n"
"background: rgb(33, 139, 14);/*qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #bbf, stop: 1 #55f);*/\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"text:\"roni\";\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;   /*COLOR DE BARRA A LA IZQUIERDA*/\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"text:\"roni\";\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,stop:0 #eee, stop:1 #ccc); /*colo de la cosa que se mueve*/\n"
"border: 1px solid #777;\n"
"width: 40px; /* ancho de la barra que se  mueve*/\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"text:\"roni\";\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"text:\"roni\";\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"text:\"roni\";\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"text:\"roni\";\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"text:\"roni\";\n"
"}")
        self.hoSli_foco.setMaximum(1)
        self.hoSli_foco.setSingleStep(1)
        self.hoSli_foco.setPageStep(1)
        self.hoSli_foco.setTracking(True)
        self.hoSli_foco.setOrientation(QtCore.Qt.Horizontal)
        self.hoSli_foco.setObjectName("hoSli_foco")
        self.horizontalLayout_13.addWidget(self.hoSli_foco)
        self.label_37 = QtWidgets.QLabel(self.widget_3)
        self.label_37.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_13.addWidget(self.label_37)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_7.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.widget_5)
        self.widget_2.setMinimumSize(QtCore.QSize(150, 180))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_27 = QtWidgets.QLabel(self.widget_2)
        self.label_27.setMaximumSize(QtCore.QSize(100, 40))
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_12.addWidget(self.label_27)
        self.btn_configVenti = QtWidgets.QPushButton(self.widget_2)
        self.btn_configVenti.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_configVenti.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_configVenti.setFont(font)
        self.btn_configVenti.setStyleSheet("QPushButton:hover {\n"
"    background-color: #DDE8E8; \n"
"    border: 1px solid #DAE7E7;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #DDE8E8; \n"
"    border: 1px solid #B1BCBC;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#B8C0C0;\n"
"    border: 1px solid #B8C0C0;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(170, 170, 127)\n"
"}")
        self.btn_configVenti.setObjectName("btn_configVenti")
        self.horizontalLayout_12.addWidget(self.btn_configVenti)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.bel_estadoVenti = QtWidgets.QLabel(self.widget_2)
        self.bel_estadoVenti.setMinimumSize(QtCore.QSize(100, 70))
        self.bel_estadoVenti.setMaximumSize(QtCore.QSize(150, 150))
        self.bel_estadoVenti.setStyleSheet("border-image: url(:/SISTEMA_CONTROL/IMAGENES/SISTEMA_CONTROL/ventilador_off.png);\n"
"")
        self.bel_estadoVenti.setText("")
        self.bel_estadoVenti.setObjectName("bel_estadoVenti")
        self.horizontalLayout_5.addWidget(self.bel_estadoVenti)
        self.label_31 = QtWidgets.QLabel(self.widget_2)
        self.label_31.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_5.addWidget(self.label_31)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_32 = QtWidgets.QLabel(self.widget_2)
        self.label_32.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_6.addWidget(self.label_32)
        self.hoSli_venti = QtWidgets.QSlider(self.widget_2)
        self.hoSli_venti.setEnabled(True)
        self.hoSli_venti.setMinimumSize(QtCore.QSize(100, 35))
        self.hoSli_venti.setMaximumSize(QtCore.QSize(120, 16777215))
        self.hoSli_venti.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: white;\n"
"height: 25px; /*ALTURA DE LA BARRA*/\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"/*background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);*/\n"
"background: rgb(33, 139, 14);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"text:\"roni\";\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;   /*COLOR DE BARRA A LA IZQUIERDA*/\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"text:\"roni\";\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,stop:0 #eee, stop:1 #ccc); /*colo de la cosa que se mueve*/\n"
"border: 1px solid #777;\n"
"width: 40px; /* ancho de la barra que se  mueve*/\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"text:\"roni\";\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"text:\"roni\";\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #058C4BCF, stop: 1 #058C4B);  /*rgb(33, 139, 14);*/\n"
"border-color: #999;\n"
"text:\"roni\";\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"text:\"roni\";\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"text:\"roni\";\n"
"}")
        self.hoSli_venti.setMaximum(1)
        self.hoSli_venti.setSingleStep(1)
        self.hoSli_venti.setPageStep(1)
        self.hoSli_venti.setProperty("value", 1)
        self.hoSli_venti.setTracking(True)
        self.hoSli_venti.setOrientation(QtCore.Qt.Horizontal)
        self.hoSli_venti.setObjectName("hoSli_venti")
        self.horizontalLayout_6.addWidget(self.hoSli_venti)
        self.label_33 = QtWidgets.QLabel(self.widget_2)
        self.label_33.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_6.addWidget(self.label_33)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addWidget(self.widget_2)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.horizontalLayout_10.addWidget(self.widget_4)
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setMinimumSize(QtCore.QSize(10, 0))
        self.label_16.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dateEdit_fecha.setDisplayFormat(_translate("Form", "ddd dd MMM yy"))
        self.timeEdit_tiempo.setDisplayFormat(_translate("Form", "hh:mm AP"))
        self.bel_temp.setText(_translate("Form", "38.00"))
        self.label_2.setText(_translate("Form", "[°C]"))
        self.label_3.setText(_translate("Form", "Control"))
        self.rb_controlManual.setText(_translate("Form", "Manual"))
        self.rb_controlAutomatico.setText(_translate("Form", "Automatico"))
        self.btn_configVenti.setText(_translate("Form", "100 [°C]"))
import IMAG_rc
