# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\itemAlarmaVista_dise.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(330, 120)
        Form.setMinimumSize(QtCore.QSize(330, 120))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.hoSli_estado = QtWidgets.QSlider(Form)
        self.hoSli_estado.setMinimumSize(QtCore.QSize(50, 20))
        self.hoSli_estado.setMaximumSize(QtCore.QSize(90, 16777215))
        self.hoSli_estado.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"/*background: white;*/\n"
"background: #393939; /*COLOR DE LA COSA QUE SE MUEVE*/\n"
"height: 15px; /*ALTURA DE LA BARRA*/\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: #393939; /*COLOR DE LA BARRA CUANDO COSA  DERECHA*/\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;   /*COLOR DE BARRA CUANDO COSA IZQUIERDA*/\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background:qlineargradient(x1:0, y1:0, x2:1, y2:1,stop:0 #eee, stop:1 #ccc); \n"
"border: 1px solid #777;\n"
"width: 40px; /* ancho de la barra que se  mueve*/\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);  /*color de la cosa cuando se mueve */\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"height: 10px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}\n"
"")
        self.hoSli_estado.setMaximum(1)
        self.hoSli_estado.setPageStep(1)
        self.hoSli_estado.setOrientation(QtCore.Qt.Horizontal)
        self.hoSli_estado.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.hoSli_estado.setObjectName("hoSli_estado")
        self.horizontalLayout_2.addWidget(self.hoSli_estado)
        self.btn_editar = QtWidgets.QPushButton(Form)
        self.btn_editar.setMinimumSize(QtCore.QSize(18, 18))
        self.btn_editar.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_editar.setStyleSheet("QPushButton {\n"
"    border-image: url(:/ALARMA/IMAGENES/ALARMA/edit_off.png);\n"
" }\n"
"QPushButton:hover {\n"
"    border-image: url(:/ALARMA/IMAGENES/ALARMA/edit_on.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/ALARMA/IMAGENES/ALARMA/edit_off.png);\n"
"}\n"
"")
        self.btn_editar.setText("")
        self.btn_editar.setObjectName("btn_editar")
        self.horizontalLayout_2.addWidget(self.btn_editar)
        self.btn_eliminar = QtWidgets.QPushButton(Form)
        self.btn_eliminar.setMinimumSize(QtCore.QSize(18, 18))
        self.btn_eliminar.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_eliminar.setStyleSheet("QPushButton {\n"
"    border-image: url(:/ALARMA/IMAGENES/ALARMA/tache_1.png);\n"
" }\n"
"QPushButton:hover {\n"
"    border-image: url(:/ALARMA/IMAGENES/ALARMA/tache_2.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(:/ALARMA/IMAGENES/ALARMA/tache_1.png);\n"
"}\n"
"")
        self.btn_eliminar.setText("")
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout_2.addWidget(self.btn_eliminar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textEdit_alarma = QtWidgets.QTextEdit(Form)
        self.textEdit_alarma.setMinimumSize(QtCore.QSize(0, 80))
        self.textEdit_alarma.setObjectName("textEdit_alarma")
        self.verticalLayout.addWidget(self.textEdit_alarma)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import IMAG_rc
